# CONFIGURACIÓN DE BASE DE DATOS EN MEMORIA H2 (Para GitHub Codespaces)
spring.datasource.url=jdbc:h2:mem:greentech_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ESTRATEGIA DE JPA E HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ACTIVAR LA CONSOLA VISUAL DE H2
spring.h2.console.enabled=true

# captura la URL real de HTTPS del entorno de Codespaces
server.forward-headers-strategy=framework

server.port=8081